[package]
name = "nitf-rs"
version = "0.1.3"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Crate to read NITF files."
homepage = "https://github.com/holmesv3/nitf-rs"
readme = "README-crates.md"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
num-complex = "0.4.3"
memmap2 = "0.5.10"
ndarray = {version = "0.15.6", features = ["serde"]}


